### ISSUE TITLE
about question 1 bootstrap

### ISSUE THREAD

**Issue by Gml717** [andyc1997/KUL-Multivariate-Statistics#2]
Why use the raw data and not het share data for the bootstrap

**Comment by andyc1997** [comment]
Sorry about that it is a typo. The data for bootstrapping is exactly the same as the data for PCA. It is calculated using guideline from question 1. The typo is because I planned to bootstrap the raw data and make calculation to arrive the transformed data but it seems too complicated (so abolished this plan).
